sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oej4TRA5zKN2moLkOHvUhiy5odIJhniFwpgdQDAdAo3PztHILzudysiHN7jB3uR1wyScr71r/USsMl9neE2oW8N0aKcN5QQzniENpRqDioKhuVEHyVwojD3NuK/0TaqlZleHbajB+FueH7VTq9Itmn1yTYjOrgxRVtgLQOvOg0jDbOaKc2YRI0Hp7VWzA38w1DDlNEUjX2qdqBd32ko7MhpzmS+FdAaJcMYnBhw3qg4cBmg9Y1GGBEunB+do7AjVhGjQaZHLJf6+a1OebUZygbmzbAi/FtgZfV7RFrGFB7+1eTwJRi8k25KzFfKTxZSeCpfeSPz9QEEFPIbRwj9SuJ7TD9n16HgIO3xgZey4gQ4zHzBF+2hwmWiLpqVPgE38hDu7n5K4YxZd+DIRhHLWKru8OKRUNMT0dp0fF9C+4KnCExI3LWibrHSJfROBmSCBo/1RfhbjImygIg0s9gGfYiSy52rgLTRzw2gPB/xVR7ppbFQfiAiRtHAbPJXZw4GGnmLpielLEaWI9je6M8iLOaaj9eqaAvkW/dfQCpXb45gF+lLf7PIWrNKa1FrWUnAzxKSoH9ejdZynr3UgykdhjsT4f5GFTpd3ydCKbKspUaUQOnfFxRJL8KYu5g/ESJSIGvG9Yc0Tj8ukhZXingczX8b6yv/92kVTVak7P6o/9i0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/In-the-Fire-of-the-Forge-A-Romance-of-Old-Nuremberg-Volume-03_5545
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy